INSERT INTO EMP (EMP_IDX, EMP_ID, EMP_PERMANENTID, EMP_JOBID, EMP_DEPARTMENTID, EMP_NAME, EMP_EMAIL,EMP_PWD,EMP_ADDRESS,EMP_PHONE,EMP_HIREDATE,EMP_DEPARTUREDATE,EMP_CAR,EMP_IMG,EMP_IMG_UP) VALUES (1, 'so여물', '경비', '경비', '경비', '송영욱', 'so@ict.co.kr', 'duanf', '서울특별시 마포구', '0000000000', '2019-01-01', '2019-01-01', '차량', '경비사진', '경비사진');

-- D-REPORT INSERT 
INSERT INTO TRIAL_DAILY (TRIAL_DAILY_IDX, TRIAL_DAILY_DATE, TRIAL_DAILY_DEBITIN, TRIAL_DAILY_DEBITOUT, TRIAL_DAILY_DEBITTOTAL,TRIAL_DAILY_CREDITIN, TRIAL_DAILY_CREDITOUT, TRIAL_DAILY_CREDITTOTAL, TRIAL_DAILY_ACCOUNT) VALUES (100, '2023-05-07',1000, 200, 800, 500, 0, 500, 'Account 1');

INSERT INTO TRIAL_DAILY (TRIAL_DAILY_IDX, TRIAL_DAILY_DATE, TRIAL_DAILY_DEBITIN, TRIAL_DAILY_DEBITOUT, TRIAL_DAILY_DEBITTOTAL, TRIAL_DAILY_CREDITIN, TRIAL_DAILY_CREDITOUT, TRIAL_DAILY_CREDITTOTAL, TRIAL_DAILY_ACCOUNT) VALUES (200, '2023-05-07',2000, 500, 1500, 0, 1000, 1000, 'Account 2');

INSERT INTO TRIAL_DAILY (TRIAL_DAILY_IDX, TRIAL_DAILY_DATE, TRIAL_DAILY_DEBITIN, TRIAL_DAILY_DEBITOUT, TRIAL_DAILY_DEBITTOTAL, TRIAL_DAILY_CREDITIN, TRIAL_DAILY_CREDITOUT, TRIAL_DAILY_CREDITTOTAL, TRIAL_DAILY_ACCOUNT) VALUES (300, '2023-05-07',500, 0, 500, 0, 500, 500, 'Account 3');

INSERT INTO TRIAL_DAILY (TRIAL_DAILY_IDX, TRIAL_DAILY_DATE, TRIAL_DAILY_DEBITIN, TRIAL_DAILY_DEBITOUT, TRIAL_DAILY_DEBITTOTAL, TRIAL_DAILY_CREDITIN, TRIAL_DAILY_CREDITOUT, TRIAL_DAILY_CREDITTOTAL, TRIAL_DAILY_ACCOUNT) VALUES (400, '2023-05-07',0, 0, 0, 0, 0, 0, 'Account 4');

INSERT INTO TRIAL_DAILY (TRIAL_DAILY_IDX, TRIAL_DAILY_DATE, TRIAL_DAILY_DEBITIN, TRIAL_DAILY_DEBITOUT, TRIAL_DAILY_DEBITTOTAL, TRIAL_DAILY_CREDITIN, TRIAL_DAILY_CREDITOUT, TRIAL_DAILY_CREDITTOTAL, TRIAL_DAILY_ACCOUNT) VALUES (500, '2023-05-07',100, 50, 50, 200, 100, 100, 'Account 5');
