/*
-- 계정생성
CREATE USER c##artpart
IDENTIFIED BY artpart;

-- 접속 권한
GRANT CONNECT, RESOURCE TO c##artpart;

-- 테이블, 시퀀스 생성 권한
GRANT CREATE TABLE TO c##artpart;
GRANT CREATE SEQUENCE TO c##artpart;

-- 테이블 스페이스 사용 권한
ALTER USER c##artpart QUOTA 10M ON USERS;
*/

DROP TABLE EMP CASCADE CONSTRAINTS;
DROP TABLE APT CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE MINONE CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE READ CASCADE CONSTRAINTS;
DROP TABLE SEESUL CASCADE CONSTRAINTS;
DROP TABLE SCHECK CASCADE CONSTRAINTS;
DROP TABLE COMPANY CASCADE CONSTRAINTS;
DROP TABLE CAR CASCADE CONSTRAINTS;
DROP TABLE PAYMENT_PUBLIC CASCADE CONSTRAINTS;
DROP TABLE PAYMENT_MEMBER CASCADE CONSTRAINTS;
DROP TABLE PAYMENT_DETAILS CASCADE CONSTRAINTS;
DROP TABLE VOTING CASCADE CONSTRAINTS;
DROP TABLE REPLY_COUNT CASCADE CONSTRAINTS;
DROP TABLE TRIAL_DAILY CASCADE CONSTRAINTS;
DROP TABLE TRIAL_MONTHLY CASCADE CONSTRAINTS;
DROP TABLE CASH_REGISTER CASCADE CONSTRAINTS;
DROP TABLE EMP_SCHEDULE CASCADE CONSTRAINTS;
DROP TABLE CAPMEETING CASCADE CONSTRAINTS;
DROP TABLE SLIP CASCADE CONSTRAINTS;

-- 1. 직원정보
CREATE TABLE EMP (
	EMP_IDX	NUMBER	NOT NULL,
	EMP_ID VARCHAR2(30) NOT NULL,
	EMP_PERMANENT_ID VARCHAR2(30) NOT NULL,
	EMP_DEPARTMENT_ID VARCHAR2(30),
	EMP_JOB_ID VARCHAR2(30),
	EMP_NAME VARCHAR2(20) NOT NULL,
	EMP_EMAIL VARCHAR2(40),
	EMP_PWD	VARCHAR2(100) NOT NULL,
	EMP_ADDRESS	VARCHAR2(100) NOT NULL,
	EMP_PHONE	VARCHAR2(12) NOT NULL,
	EMP_HIREDATE DATE DEFAULT SYSDATE NOT NULL,
	EMP_DEPARTUREDATE DATE,
	EMP_CAR	VARCHAR2(40),
	EMP_IMG	VARCHAR2(400),
	EMP_IMG_UP	VARCHAR2(400),	

CONSTRAINT PK_EMP_IDX PRIMARY KEY (EMP_IDX)
);

COMMENT ON COLUMN EMP.EMP_IDX IS '직원등록번호';
COMMENT ON COLUMN EMP.EMP_ID IS '직원아이디';
COMMENT ON COLUMN EMP.EMP_PERMANENT_ID IS '사원 구분';
COMMENT ON COLUMN EMP.EMP_DEPARTMENT_ID IS '직급';
COMMENT ON COLUMN EMP.EMP_JOB_ID IS '소속';
COMMENT ON COLUMN EMP.EMP_NAME IS '사원명';
COMMENT ON COLUMN EMP.EMP_EMAIL IS '이메일 주소';
COMMENT ON COLUMN EMP.EMP_PWD IS '비밀번호';
COMMENT ON COLUMN EMP.EMP_ADDRESS IS '주소';
COMMENT ON COLUMN EMP.EMP_PHONE IS '연락처';
COMMENT ON COLUMN EMP.EMP_HIREDATE IS '입사일';
COMMENT ON COLUMN EMP.EMP_DEPARTUREDATE IS '퇴사일';
COMMENT ON COLUMN EMP.EMP_CAR IS '차량번호';
COMMENT ON COLUMN EMP.EMP_IMG IS '사진';
COMMENT ON COLUMN EMP.EMP_IMG_UP IS '사진(수정)';

-- 2. 아파트 정보
CREATE TABLE APT (
	APT_IDX	NUMBER NOT NULL,
	APT_ROAD VARCHAR2(1000),
	APT_ADD	VARCHAR2(1000),
	APT_COUNT NUMBER,
	APT_RCOUNT NUMBER,
	APT_PHONE VARCHAR2(30),
    
CONSTRAINT PK_APT_IDX PRIMARY KEY (APT_IDX)
);

COMMENT ON COLUMN APT.APT_IDX IS '아파트번호';
COMMENT ON COLUMN APT.APT_ROAD IS '도로명주소';
COMMENT ON COLUMN APT.APT_ADD IS '지번주소';
COMMENT ON COLUMN APT.APT_COUNT IS '총 세대수';
COMMENT ON COLUMN APT.APT_RCOUNT IS '거주중인세대수';
COMMENT ON COLUMN APT.APT_PHONE IS '관리소연락처';

-- 3. 입주민 정보
CREATE TABLE MEMBER (
	MEMBER_IDX NUMBER NOT NULL,
	APT_IDX	NUMBER NOT NULL,
	MEMBER_DONG	VARCHAR2(30) NOT NULL,
	MEMBER_HO	VARCHAR2(30) NOT NULL,
	MEMBER_NAME	VARCHAR2(30),
	MEMBER_ID	VARCHAR2(30) NOT NULL,
	MEMBER_PASSWORD	VARCHAR2(30) NOT NULL,
	MEMBER_PHONE	VARCHAR2(30),
	MEMBER_LOGINOK	CHAR(1)	DEFAULT 'N'	NOT NULL,
	MEMBER_MYCAR1	VARCHAR2(20),
	MEMBER_MYCAR2	VARCHAR2(20),
    
CONSTRAINT PK_MEMBER_IDX PRIMARY KEY (MEMBER_IDX),
CONSTRAINT FK_APT_IDX FOREIGN KEY (APT_IDX) REFERENCES APT
);

COMMENT ON COLUMN MEMBER.MEMBER_IDX IS '입주민 번호';
COMMENT ON COLUMN MEMBER.APT_IDX IS '아파트번호';
COMMENT ON COLUMN MEMBER.MEMBER_DONG IS '동';
COMMENT ON COLUMN MEMBER.MEMBER_HO IS '호수';
COMMENT ON COLUMN MEMBER.MEMBER_NAME IS '이름';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PASSWORD IS '비밀번호';
COMMENT ON COLUMN MEMBER.MEMBER_PHONE IS '핸드폰번호';
COMMENT ON COLUMN MEMBER.MEMBER_LOGINOK IS '입주완료여부';
COMMENT ON COLUMN MEMBER.MEMBER_MYCAR1 IS '등록차번호1';
COMMENT ON COLUMN MEMBER.MEMBER_MYCAR2 IS '등록차번호2';

-- 4. 민원 글쓰기
CREATE TABLE MINONE(
	MIN_IDX	NUMBER NOT NULL,
	MEMBER_IDX NUMBER NOT NULL,
	MIN_TITLE VARCHAR2(30) NOT NULL,
	MIN_TYPE VARCHAR2(2000) NOT NULL,
	MIN_STATUS VARCHAR2(30)	DEFAULT '처리예정' NOT NULL,
	MIN_RES	VARCHAR2(2000),
	MIN_FILE VARCHAR2(400),
	MIN_RENAME VARCHAR2(100),
	MIN_CATEGORY VARCHAR2(30) NOT NULL,
    
CONSTRAINT PK_MIN_IDX PRIMARY KEY (MIN_IDX),
CONSTRAINT FK_MINMEMBER_IDX FOREIGN KEY (MEMBER_IDX) REFERENCES MEMBER
);

COMMENT ON COLUMN MINONE.MIN_IDX IS '민원번호';
COMMENT ON COLUMN MINONE.MEMBER_IDX IS '입주민 번호';
COMMENT ON COLUMN MINONE.MIN_TITLE IS '민원제목';
COMMENT ON COLUMN MINONE.MIN_TYPE IS '민원내용';
COMMENT ON COLUMN MINONE.MIN_STATUS IS '처리상황';
COMMENT ON COLUMN MINONE.MIN_RES IS '관리자답변';
COMMENT ON COLUMN MINONE.MIN_FILE IS '원본파일';
COMMENT ON COLUMN MINONE.MIN_RENAME IS '변경파일';
COMMENT ON COLUMN MINONE.MIN_CATEGORY IS '카테고리';

-- 5. 검침
CREATE TABLE READ (
	READIDX NUMBER NOT NULL,
	MEMBER_IDX NUMBER NOT NULL,
	ELECTRIC NUMBER NOT NULL,
	HOTWATER NUMBER NOT NULL,
	WATER NUMBER NOT NULL,
	HEAT NUMBER NOT NULL,
	READDATE DATE DEFAULT SYSDATE	NOT NULL,

CONSTRAINT PK_READIDX  PRIMARY KEY (READIDX),    
CONSTRAINT FK_READMEMBER_IDX FOREIGN KEY (MEMBER_IDX) REFERENCES MEMBER   
);

COMMENT ON COLUMN READ.MEMBER_IDX IS '입주민 번호';
COMMENT ON COLUMN READ.ELECTRIC IS '전기 당월지침';
COMMENT ON COLUMN READ.HOTWATER IS '온수 당월지침';
COMMENT ON COLUMN READ.WATER IS '수도 당월지침';
COMMENT ON COLUMN READ.HEAT IS '난방 당월지침';
COMMENT ON COLUMN READ.READDATE IS '날짜';

-- 6. 공지사항
CREATE TABLE NOTICE (
	NOTICEIDX NUMBER NOT NULL,
	WIRITER NUMBER NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	CONTENT VARCHAR2(2000) NOT NULL,
	NOTICEDATE	DATE DEFAULT SYSDATE NOT NULL,

CONSTRAINT PK_NOTICE_IDX PRIMARY KEY (NOTICEIDX),
CONSTRAINT FK_MEMBERNOTICE_IDX FOREIGN KEY (WIRITER) REFERENCES EMP (EMP_IDX)     
);

COMMENT ON COLUMN NOTICE.NOTICEIDX IS '공지글 번호';
COMMENT ON COLUMN NOTICE.WIRITER IS '직원등록번호';
COMMENT ON COLUMN NOTICE.TITLE IS '제목';
COMMENT ON COLUMN NOTICE.CONTENT IS '내용';
COMMENT ON COLUMN NOTICE.NOTICEDATE IS '작성일자';

-- 7. 시설관리
CREATE TABLE SEESUL (
	SIDX NUMBER NOT NULL,
	SCATEGORY VARCHAR2(10) NOT NULL,
	SDATE DATE	DEFAULT SYSDATE	NOT NULL,
	SWIRITER NUMBER	NOT NULL,

CONSTRAINT PK_SIDX PRIMARY KEY (SIDX),
CONSTRAINT FK_SMEMBER_IDX FOREIGN KEY (SWIRITER) REFERENCES EMP (EMP_IDX)
);
COMMENT ON COLUMN SEESUL.SIDX IS '글 번호';
COMMENT ON COLUMN SEESUL.SCATEGORY IS '점검 항목';
COMMENT ON COLUMN SEESUL.SDATE IS '점검일자';
COMMENT ON COLUMN SEESUL.SWIRITER IS '직원등록번호';

-- 8. 체크리스트
CREATE TABLE SCHECK (
	SCHECKIDX NUMBER NOT NULL,
	SIDX NUMBER NOT NULL,
	SCHECK NUMBER NOT NULL,
	SRESULT CHAR(1) NOT NULL,
	SPROCESS VARCHAR(50),

CONSTRAINT PK_SCHECKIDX  PRIMARY KEY (SCHECKIDX), 
CONSTRAINT FK_SIDX FOREIGN KEY (SIDX) REFERENCES SEESUL   
);

COMMENT ON COLUMN SCHECK.SIDX IS '글 번호';
COMMENT ON COLUMN SCHECK.SCHECK IS '점검사항';
COMMENT ON COLUMN SCHECK.SRESULT IS '결과';
COMMENT ON COLUMN SCHECK.SPROCESS IS '처리';

-- 9. 외부업체
CREATE TABLE COMPANY (
	COMPANYIDX	NUMBER NOT NULL,
	NAME VARCHAR2(50) NOT NULL,
	ITEM VARCHAR2(50) NOT NULL,
	PHONE VARCHAR2(20) NOT NULL,
	ADDRESS	VARCHAR2(300) NOT NULL,
	COMPANYDATE DATE DEFAULT SYSDATE NOT NULL,

CONSTRAINT PK_COMPANYIDX PRIMARY KEY (COMPANYIDX)
);

COMMENT ON COLUMN COMPANY.COMPANYIDX IS '번호';
COMMENT ON COLUMN COMPANY.NAME IS '업체명';
COMMENT ON COLUMN COMPANY.ITEM IS '취급품목';
COMMENT ON COLUMN COMPANY.PHONE IS '전화번호';
COMMENT ON COLUMN COMPANY.ADDRESS IS '업체주소';
COMMENT ON COLUMN COMPANY.COMPANYDATE IS '승인일';

-- 10. 차량관리
CREATE TABLE CAR (
	CAR_NUMBER VARCHAR2(20),
	MEMBER_IDX NUMBER,
	EMP_ID_CAR VARCHAR(20),
	CAR_DIVISION_ID	VARCHAR(30) NOT NULL,
	CAR_PHONE VARCHAR2(30),
	CAR_ENROLLDATE DATE	DEFAULT SYSDATE,
	CAR_CHANGEDATE DATE,
	CAR_TYPE VARCHAR2(100),
	CAR_NOTE VARCHAR2(200),
	CAR_STARTDATE DATE,
	CAR_ENDDATE	DATE,
    
CONSTRAINT PK_CAR_NUMBER PRIMARY KEY (CAR_NUMBER)    
);

COMMENT ON COLUMN CAR.CAR_NUMBER IS '차량 번호';
COMMENT ON COLUMN CAR.MEMBER_IDX IS '입주민번호';
COMMENT ON COLUMN CAR.EMP_ID_CAR IS '사원 번호(사번)';
COMMENT ON COLUMN CAR.CAR_DIVISION_ID IS '차량 구분';
COMMENT ON COLUMN CAR.CAR_PHONE IS '차량 주인 전화 번호';
COMMENT ON COLUMN CAR.CAR_ENROLLDATE IS '차량 등록 일시';
COMMENT ON COLUMN CAR.CAR_CHANGEDATE IS '차량 수정 일시';
COMMENT ON COLUMN CAR.CAR_TYPE IS '차종';
COMMENT ON COLUMN CAR.CAR_NOTE IS '비고';
COMMENT ON COLUMN CAR.CAR_STARTDATE IS '방문 시작 날짜';
COMMENT ON COLUMN CAR.CAR_ENDDATE IS '방문 종료 날짜';

-- 11. 공동 관리비
CREATE TABLE PAYMENT_PUBLIC (
	PPIDX NUMBER NOT NULL,
	PPDATE	DATE DEFAULT SYSDATE NOT NULL,
	PPFEE NUMBER,
    
CONSTRAINT PK_PPIDX PRIMARY KEY (PPIDX)     
);

COMMENT ON COLUMN PAYMENT_PUBLIC.PPIDX  IS '관리비번호';
COMMENT ON COLUMN PAYMENT_PUBLIC.PPDATE IS '일자';
COMMENT ON COLUMN PAYMENT_PUBLIC.PPFEE IS '일반관리비';

-- 12. 개별 관리비
CREATE TABLE PAYMENT_MEMBER (
	PMIDX NUMBER NOT NULL,
	MEMBER_NO NUMBER NOT NULL,
	PMDATE	DATE DEFAULT SYSDATE,
	PMHEAT	NUMBER,
	PMONSU NUMBER,
	PMGAS NUMBER,
	PMELEC	NUMBER,
	PMWATER NUMBER,
	PMSEPTIC NUMBER,
	PMWASTE NUMBER,
	PMOPERCOST NUMBER,
	PMINSURE NUMBER,
	
CONSTRAINT PK_PMIDX PRIMARY KEY (PMIDX),
CONSTRAINT FK_PAMEMBER_IDX FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER (MEMBER_IDX)
);

COMMENT ON COLUMN PAYMENT_MEMBER.PMIDX  IS '개별관리비번호';
COMMENT ON COLUMN PAYMENT_MEMBER.MEMBER_NO IS '입주민번호';
COMMENT ON COLUMN PAYMENT_MEMBER.PMDATE IS '일자';
COMMENT ON COLUMN PAYMENT_MEMBER.PMHEAT IS '난방비';
COMMENT ON COLUMN PAYMENT_MEMBER.PMONSU  IS '급탕비(온수)';
COMMENT ON COLUMN PAYMENT_MEMBER.PMGAS  IS '가스사용';
COMMENT ON COLUMN PAYMENT_MEMBER.PMELEC IS '전기료';
COMMENT ON COLUMN PAYMENT_MEMBER.PMWATER IS '수도료';
COMMENT ON COLUMN PAYMENT_MEMBER.PMSEPTIC IS '정화조오물수수료';
COMMENT ON COLUMN PAYMENT_MEMBER.PMWASTE  IS '생활폐기물수수료';
COMMENT ON COLUMN PAYMENT_MEMBER.PMOPERCOST IS '관리위원회운영비';
COMMENT ON COLUMN PAYMENT_MEMBER.PMINSURE IS '건물보험료';


-- 13. 투표설문
CREATE TABLE VOTING (
	VOTING_IDX NUMBER NOT NULL,
	CATEGORY VARCHAR2(100) NOT NULL,
	TITLE VARCHAR2(100)	NOT NULL,
	CONTENT	VARCHAR2(2000) NOT NULL,
	START_TIME DATE,
	END_TIME DATE,
	ANSWER1	VARCHAR2(500) NOT NULL,
	ANSWER2	VARCHAR2(500) NOT NULL,
	ANSWER3	VARCHAR2(500),
	ANSWER4	VARCHAR2(500),
	ANSWER5	VARCHAR2(500),
	VOTING_WRITER VARCHAR2(50) NOT NULL,
	VOTING_START VARCHAR2(10) DEFAULT 'N' NOT NULL,
    
CONSTRAINT PK_VOTING_IDX PRIMARY KEY (VOTING_IDX)     
);

COMMENT ON COLUMN VOTING.VOTING_IDX IS '설문 번호';
COMMENT ON COLUMN VOTING.CATEGORY IS '카테고리';
COMMENT ON COLUMN VOTING.TITLE IS '제목';
COMMENT ON COLUMN VOTING.CONTENT IS '내용';
COMMENT ON COLUMN VOTING.START_TIME IS '투표설문 시작시간';
COMMENT ON COLUMN VOTING.END_TIME IS '투표설문 종료시간';
COMMENT ON COLUMN VOTING.ANSWER1 IS '답변1';
COMMENT ON COLUMN VOTING.ANSWER2 IS '답변2';
COMMENT ON COLUMN VOTING.ANSWER3 IS '답변3';
COMMENT ON COLUMN VOTING.ANSWER4 IS '답변4';
COMMENT ON COLUMN VOTING.ANSWER5 IS '답변5';
COMMENT ON COLUMN VOTING.VOTING_WRITER IS '작성자';
COMMENT ON COLUMN VOTING.VOTING_START IS '투표 마감여부';

-- 14. 투표설문 관리
CREATE TABLE REPLY_COUNT (
	MEMBER_IDX NUMBER NOT NULL,
	VOTING_IDX NUMBER NOT NULL,
	REPLY_ID NUMBER NOT NULL,
    
CONSTRAINT PK_REPLY_COUNT PRIMARY KEY (MEMBER_IDX, VOTING_IDX),
CONSTRAINT FK_REPLY_MEMBER FOREIGN KEY(MEMBER_IDX) REFERENCES MEMBER ON DELETE CASCADE,
CONSTRAINT FK_REPLY_VOTING FOREIGN KEY(VOTING_IDX) REFERENCES VOTING ON DELETE CASCADE

);

COMMENT ON COLUMN REPLY_COUNT.MEMBER_IDX IS '입주민 번호';
COMMENT ON COLUMN REPLY_COUNT.VOTING_IDX IS '설문 번호';


-- 15. 일계표
CREATE TABLE TRIAL_DAILY (
	TDIDX NUMBER NOT NULL,
	TDDATE DATE DEFAULT SYSDATE NOT NULL,
	TDDEBITIN NUMBER NOT NULL,
	TDDEBITOUT NUMBER,
	TDDEBITTOTAL NUMBER,
	TDCREDITIN NUMBER,
	TDCREDITOUT NUMBER,
	TDCREDITTOTAL NUMBER,
	TRIAL_DAILY_ACCOUNT VARCHAR2(300),
    
CONSTRAINT PK_TDIDX  PRIMARY KEY (TDIDX)
);

COMMENT ON COLUMN TRIAL_DAILY.TDIDX IS '일계표번호';
COMMENT ON COLUMN TRIAL_DAILY.TDDATE IS '일자';
COMMENT ON COLUMN TRIAL_DAILY.TDDEBITIN IS '차변입금';
COMMENT ON COLUMN TRIAL_DAILY.TDDEBITOUT IS '차변대체';
COMMENT ON COLUMN TRIAL_DAILY.TDDEBITTOTAL IS '차변합계';
COMMENT ON COLUMN TRIAL_DAILY.TDCREDITIN IS '대변입금';
COMMENT ON COLUMN TRIAL_DAILY.TDCREDITOUT IS '대변대체';
COMMENT ON COLUMN TRIAL_DAILY.TDCREDITTOTAL IS '대변합계';

COMMENT ON COLUMN TRIAL_DAILY.TRIAL_DAILY_ACCOUNT IS '계정과목';

-- 16. 월계표
CREATE TABLE TRIAL_MONTHLY (
	TMIDX NUMBER NOT NULL,
	TMDATE DATE DEFAULT SYSDATE NOT NULL,
	TMDEBITIN NUMBER NOT NULL,
	TMDEBITOUT NUMBER,
	TMDEBITTOTAL NUMBER,
	TMCREDITIN NUMBER,
	TMCREDITOUT NUMBER,
	TMCREDITTOTAL NUMBER,
	TRIAL_MONTHLY_ACCOUNT VARCHAR2(300),
    
CONSTRAINT PK_TMIDX PRIMARY KEY (TMIDX)    
);

COMMENT ON COLUMN TRIAL_MONTHLY.TMIDX IS '일계표번호';
COMMENT ON COLUMN TRIAL_MONTHLY.TMDATE IS '일자';
COMMENT ON COLUMN TRIAL_MONTHLY.TMDEBITIN IS '차변입금';
COMMENT ON COLUMN TRIAL_MONTHLY.TMDEBITOUT IS '차변대체';
COMMENT ON COLUMN TRIAL_MONTHLY.TMDEBITOUT IS '차변합계';
COMMENT ON COLUMN TRIAL_MONTHLY.TMCREDITIN IS '대변입금';
COMMENT ON COLUMN TRIAL_MONTHLY.TMCREDITOUT  IS '대변대체';
COMMENT ON COLUMN TRIAL_MONTHLY.TMCREDITTOTAL  IS '대변합계';
COMMENT ON COLUMN TRIAL_MONTHLY.TRIAL_MONTHLY_ACCOUNT IS '계정과목';

-- 17. 전표
CREATE TABLE SLIP (
	SLIPIDX NUMBER NOT NULL,
	SLIPDATE DATE DEFAULT SYSDATE	NOT NULL,
	SLIPNO	VARCHAR2(20) NOT NULL,
	SLIPWRITER VARCHAR@(50) NOT NULL,
	SLIPTYPE VARCHAR2(10),
	SLIPITEM VARCHAR2(300),
	SLIPCOMP VARCHAR2(300),
	SLIPBRIF VARCHAR2(300),
	SLIPCASH NUMBER,
	SLIPNOTE VARCHAR2(500),
	
CONSTRAINT PK_SLIPIDX PRIMARY KEY (SLIPIDX)      
);

COMMENT ON COLUMN SLIP.SLIPWRITER IS '작성자';
COMMENT ON COLUMN SLIP.SLIPIDX  IS '등록번호';
COMMENT ON COLUMN SLIP.SLIPDATE IS '일자';
COMMENT ON COLUMN SLIP.SLIPNO IS '전표번호';
COMMENT ON COLUMN SLIP.SLIPTYPE IS '전표종류';
COMMENT ON COLUMN SLIP.SLIPITEM IS '과목';
COMMENT ON COLUMN SLIP.SLIPCOMP IS '항목';
COMMENT ON COLUMN SLIP.SLIPBRIF IS '적요';
COMMENT ON COLUMN SLIP.SLIPCASH IS '금액';
COMMENT ON COLUMN SLIP.SLIPNOTE IS '비고';

-- 18. 현금 출납부
CREATE TABLE CASH_REGISTER (
	CRIDX NUMBER NOT NULL,
	CRDATE DATE DEFAULT SYSDATE,
	CRIN NUMBER,
	CROUT NUMBER,
	CRCASH NUMBER,
	CRNOTE VARCHAR2(500),
	CRWRITER VARCHAR2(20) NOT NULL,

CONSTRAINT PK_CRIDX PRIMARY KEY (CRIDX)     
);

COMMENT ON COLUMN CASH_REGISTER.CRIDX IS '등록번호';
COMMENT ON COLUMN CASH_REGISTER.CRDATE IS '일자';
COMMENT ON COLUMN CASH_REGISTER.CRIN IS '수입';
COMMENT ON COLUMN CASH_REGISTER.CROUT IS '지출';
COMMENT ON COLUMN CASH_REGISTER.CRCASH IS '차인잔액';
COMMENT ON COLUMN CASH_REGISTER.CRNOTE IS '비고';
COMMENT ON COLUMN CASH_REGISTER.CRWRITER IS '작성자';

-- 19. 직원 스케줄 관리
CREATE TABLE EMP_SCHEDULE (
	SCHEDULE_IDX NUMBER	NOT NULL,
	EMP_IDX	NUMBER NOT NULL,
	EMP_STARTDATE DATE NOT NULL,
	EMP_ENDDATE	DATE,
	EMP_STARTTIME DATE,
	EMP_ENDTIME	DATE,
    
CONSTRAINT PK_SCHEDULE_IDX PRIMARY KEY (SCHEDULE_IDX),
CONSTRAINT FK_SCHEDULE_EMP_IDX FOREIGN KEY(EMP_IDX) REFERENCES MEMBER ON DELETE CASCADE
);

COMMENT ON COLUMN EMP_SCHEDULE.SCHEDULE_IDX IS '직원스케줄순번';
COMMENT ON COLUMN EMP_SCHEDULE.EMP_IDX IS '직원등록번호';
COMMENT ON COLUMN EMP_SCHEDULE.EMP_STARTDATE IS '근무시작날짜(LocalDate)';
COMMENT ON COLUMN EMP_SCHEDULE.EMP_ENDDATE IS '근무 종료날짜';
COMMENT ON COLUMN EMP_SCHEDULE.EMP_STARTTIME IS '근무 시작 시간';
COMMENT ON COLUMN EMP_SCHEDULE.EMP_ENDTIME IS '근무 종료 시간';

-- 20. 대표자 회의
CREATE TABLE CAPMEETING (
	MEETING_IDX	NUMBER	NOT NULL,
	MEETING_TIME DATE,
	MEETING_TITLE VARCHAR2(1000) NOT NULL,
	MEETING_CONTENT	VARCHAR2(1000) NOT NULL,
	MEETING_ID	NUMBER NOT NULL,
	MEETING_OPEN CHAR(1) DEFAULT 'N' NOT NULL,

CONSTRAINT PK_MEETING_IDX PRIMARY KEY (MEETING_IDX)
);

COMMENT ON COLUMN CAPMEETING.MEETING_IDX IS '설문 번호';
COMMENT ON COLUMN CAPMEETING.MEETING_TIME IS '회의일자';
COMMENT ON COLUMN CAPMEETING.MEETING_TITLE IS '제목';
COMMENT ON COLUMN CAPMEETING.MEETING_CONTENT IS '내용';
COMMENT ON COLUMN CAPMEETING.MEETING_ID IS '작성자';
COMMENT ON COLUMN CAPMEETING.MEETING_OPEN IS '공지 여부';

-- 21. 관리비 납부
CREATE TABLE PAYMENT_DETAILS (
	DETAIL_IDX NUMBER NOT NULL,
	MEMBER_IDX NUMBER NOT NULL,
	PAYMENT_DATE DATE DEFAULT SYSDATE NOT NULL,
	PAYMENT_DADLINE	DATE NOT NULL,
	PAYMENT_MONEY NUMBER NOT NULL,
	PAYMENT_BANK VARCHAR2(40) NOT NULL,
	BANK_NUMBER	VARCHAR2(100) NOT NULL,
	PAYMENT_STATUS VARCHAR2(20) DEFAULT '미납' NOT NULL,

CONSTRAINT PK_DETAIL_IDX PRIMARY KEY (DETAIL_IDX),
CONSTRAINT FK_MEETING_IDX FOREIGN KEY (MEMBER_IDX) REFERENCES MEMBER
);

COMMENT ON COLUMN PAYMENT_DETAILS.DETAIL_IDX  IS '관리비 번호';
COMMENT ON COLUMN PAYMENT_DETAILS.MEMBER_IDX IS '입주민 번호';
COMMENT ON COLUMN PAYMENT_DETAILS.PAYMENT_DATE IS '결제일자';
COMMENT ON COLUMN PAYMENT_DETAILS.PAYMENT_DADLINE IS '납부마감일';
COMMENT ON COLUMN PAYMENT_DETAILS.PAYMENT_MONEY IS '결제금액';
COMMENT ON COLUMN PAYMENT_DETAILS.PAYMENT_BANK IS '금융사';
COMMENT ON COLUMN PAYMENT_DETAILS.BANK_NUMBER IS '납부 계좌번호';
COMMENT ON COLUMN PAYMENT_DETAILS.PAYMENT_STATUS IS '진행상태';

------------시퀀스----------------------
--삭제
DROP SEQUENCE APT_IDX;
DROP SEQUENCE MEMBER_IDX;
DROP SEQUENCE MIN_IDX;
DROP SEQUENCE VOTING_IDX;
DROP SEQUENCE NOTICE_IDX;
DROP SEQUENCE COMPANY_IDX;
DROP SEQUENCE S_IDX;
DROP SEQUENCE SCHEDULE_IDX;
DROP SEQUENCE EMP_IDX;
DROP SEQUENCE MEETING_IDX;
DROP SEQUENCE SCHECK_IDX;
DROP SEQUENCE READ_IDX;
DROP SEQUENCE DETAIL_IDX;
DROP SEQUENCE PPIDX;
DROP SEQUENCE PMIDX;
DROP SEQUENCE TDIDX;
DROP SEQUENCE TMIDX;
DROP SEQUENCE SLIPIDX;
DROP SEQUENCE CRIDX;


-- 1. 아파트
CREATE SEQUENCE APT_IDX
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

-- 2. 입주민 
CREATE SEQUENCE MEMBER_IDX
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

-- 3. 민원 글  
CREATE SEQUENCE MIN_IDX
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

-- 4. 회의투표설문  
CREATE SEQUENCE VOTING_IDX
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

-- 5. 대표자 회의
CREATE SEQUENCE MEETING_IDX
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

-- 6. 관리비 납부 내역
CREATE SEQUENCE DETAIL_IDX
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

----------------------------직원 시퀀스-------------------------------


-- 7. 공공관리비
CREATE SEQUENCE PPIDX
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

-- 8. 개별 관리비
CREATE SEQUENCE PMIDX
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

-- 9. 전표
CREATE SEQUENCE SLIPIDX
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

-- 10. 일계표
CREATE SEQUENCE TDIDX
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

-- 11. 월계표
CREATE SEQUENCE TMIDX
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

-- 12. 현금 출납부
CREATE SEQUENCE CRIDX
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

-- 13. 공지사항
CREATE SEQUENCE NOTICE_IDX
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

-- 14. 직원정보
CREATE SEQUENCE EMP_IDX
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

-- 15. 외부업체
CREATE SEQUENCE COMPANY_IDX
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

-- 16. 시설 관리
CREATE SEQUENCE S_IDX
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

-- 17. 직원스케줄
CREATE SEQUENCE SCHEDULE_IDX
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;


-- 18. 검침
CREATE SEQUENCE READ_IDX
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

-- 19. 시설관리 체크
CREATE SEQUENCE SCHECK_IDX
INCREMENT BY 1
START WITH 1
NOMAXVALUE
NOCYCLE
NOCACHE;

COMMIT;




