#properties 와 yml 이 같이있으면 properties 가 우선
server:
  port: 8887
  servlet:
    encoding:
      charset: utf-8
      force: true
      enabled: true

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.Oracle12cDialect


  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: c##artpart
    password: artpart

# debug level 로 시큐리티 필터 로깅 설정
logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        type:
          descriptor:
            sql: trace


# secreykey
org:
  ict:
    secretKey: n2r5u8x/A%D*G-KaPdSgVkYp3s6v9y$B&E(H+MbQeThWmZq4t7w!z%C*F-J@NcRf

